#!/bin/bash
if [ "$(id -u)" -ne 0 ]; then
    exec sudo -- "$0" "$@"
fi

CURR_TTY="/dev/tty1"
APP_NAME="ZRam Manager for R36S"

printf "\033c" > "$CURR_TTY"
printf "\e[?25l" > "$CURR_TTY"
dialog --clear
export TERM=linux
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

height="15"
width="55"

if test ! -z "$(cat /home/ark/.config/.DEVICE 2>/dev/null | grep RG503 | tr -d '\0')"
then
  height="20"
  width="60"
fi

if [[ ! -e "/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
    if test ! -z "$(cat /home/ark/.config/.DEVICE 2>/dev/null | grep RG503 | tr -d '\0')"
    then
        setfont /usr/share/consolefonts/Lat7-TerminusBold20x10.psf.gz
    else
        setfont /usr/share/consolefonts/Lat7-TerminusBold22x11.psf.gz
    fi
else
    setfont /usr/share/consolefonts/Lat7-Terminus16.psf.gz
fi

pkill -9 -f gptokeyb || true
pkill -9 -f osk.py || true

printf "\033c" > "$CURR_TTY"
printf "Starting ZRam Manager\nPlease wait..." > "$CURR_TTY"
sleep 1

BACKTITLE="ZRam Manager for R36S"

ExitMenu() {
  printf "\033c" > "$CURR_TTY"
  printf "\e[?25h" > "$CURR_TTY"
  if [[ ! -z $(pgrep -f gptokeyb) ]]; then
    pgrep -f gptokeyb | sudo xargs kill -9
  fi
  if [[ ! -e "/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
    setfont /usr/share/consolefonts/Lat7-Terminus20x10.psf.gz
  fi
  exit 0
}

GetSystemRAM() {
    local MEM_TOTAL_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    echo $((MEM_TOTAL_KB / 1024))
}

GetAvailableAlgorithms() {
    local ALGO_LIST=""
    
    if [ ! -b /dev/zram0 ]; then
        modprobe zram num_devices=1 2>/dev/null
        sleep 0.5
    fi
    
    if [ -f /sys/block/zram0/comp_algorithm ]; then
        ALGO_LIST=$(cat /sys/block/zram0/comp_algorithm | tr -d '[]' | xargs -n1 | sort -u)
    fi
    
    if [ -z "$ALGO_LIST" ]; then
        echo "lz4"
        echo "lzo"
        echo "zstd"
    else
        echo "$ALGO_LIST"
    fi
}

GetFastestAlgorithm() {
    local ALGOS=$(GetAvailableAlgorithms)
    
    if echo "$ALGOS" | grep -qx "lz4"; then
        echo "lz4"
    elif echo "$ALGOS" | grep -qx "lzo"; then
        echo "lzo"
    elif echo "$ALGOS" | grep -qx "lzo-rle"; then
        echo "lzo-rle"
    elif echo "$ALGOS" | grep -qx "zstd"; then
        echo "zstd"
    elif echo "$ALGOS" | grep -qx "deflate"; then
        echo "deflate"
    else
        echo "$ALGOS" | head -n1
    fi
}

GetOptimalZramSize() {
    local SYSTEM_RAM=$1
    local OPTIMAL_SIZE=$((SYSTEM_RAM / 2))
    
    if [ $OPTIMAL_SIZE -lt 256 ]; then
        OPTIMAL_SIZE=256
    fi
    
    if [ $OPTIMAL_SIZE -gt 2048 ]; then
        OPTIMAL_SIZE=2048
    fi
    
    echo $OPTIMAL_SIZE
}

CheckZramStatus() {
    if [ -b /dev/zram0 ]; then
        local SIZE=$(cat /sys/block/zram0/disksize 2>/dev/null)
        if [ "$SIZE" -gt 0 ] 2>/dev/null; then
            if swapon -s | grep -q zram0; then
                local SIZE_MB=$((SIZE / 1024 / 1024))
                local ALGO=$(cat /sys/block/zram0/comp_algorithm 2>/dev/null | grep -oP '\[\K[^\]]+')
                [ -z "$ALGO" ] && ALGO="unknown"
                
                local USED=0
                if [ -f /sys/block/zram0/mm_stat ]; then
                    USED=$(awk '{print $1}' /sys/block/zram0/mm_stat 2>/dev/null)
                fi
                local USED_MB=$((USED / 1024 / 1024))
                
                echo "ACTIVE|${SIZE_MB}|${ALGO}|${USED_MB}"
                return 0
            fi
        fi
    fi
    echo "INACTIVE|0|none|0"
    return 1
}

DisableZram() {
    if [ -b /dev/zram0 ]; then
        swapoff /dev/zram0 2>/dev/null
        echo 1 > /sys/block/zram0/reset 2>/dev/null
        rmmod zram 2>/dev/null
    fi
    
    RemoveZramAutostart
    
    rm -f /etc/zram.conf 2>/dev/null
    
    return 0
}

SaveZramConfig() {
    local SIZE_MB=$1
    local ALGO=$2
    
    cat > /etc/zram.conf << EOF
# ZRam Configuration for R36S
# Auto-generated by ZRam Manager
ZRAM_SIZE_MB=${SIZE_MB}
ZRAM_ALGORITHM=${ALGO}
EOF
    
    chmod 644 /etc/zram.conf
}

LoadZramConfig() {
    if [ -f /etc/zram.conf ]; then
        source /etc/zram.conf
        echo "${ZRAM_SIZE_MB}|${ZRAM_ALGORITHM}"
        return 0
    fi
    return 1
}

SetupZramAutostart() {
    local SCRIPT_PATH="/usr/local/bin/zram-autostart.sh"
    local SERVICE_PATH="/etc/systemd/system/zram-swap.service"
    
    cat > "$SCRIPT_PATH" << 'EOF'
#!/bin/bash

ZRAM_SIZE_MB=512
ZRAM_ALGORITHM=lz4

if [ -f /etc/zram.conf ]; then
    source /etc/zram.conf
fi

modprobe zram num_devices=1 2>/dev/null

for i in {1..10}; do
    if [ -b /dev/zram0 ]; then
        break
    fi
    sleep 0.5
done

if [ ! -b /dev/zram0 ]; then
    echo "ERROR: Cannot create /dev/zram0"
    exit 1
fi

if [ -f /sys/block/zram0/comp_algorithm ]; then
    if grep -q "$ZRAM_ALGORITHM" /sys/block/zram0/comp_algorithm; then
        echo "$ZRAM_ALGORITHM" > /sys/block/zram0/comp_algorithm 2>/dev/null
    fi
fi

SIZE_BYTES=$((ZRAM_SIZE_MB * 1024 * 1024))
echo "$SIZE_BYTES" > /sys/block/zram0/disksize

mkswap /dev/zram0 >/dev/null 2>&1
swapon -p 5 /dev/zram0

exit 0
EOF
    
    chmod +x "$SCRIPT_PATH"
    
    cat > "$SERVICE_PATH" << EOF
[Unit]
Description=ZRam Compressed Swap for R36S
Documentation=man:zram(4)
DefaultDependencies=no
After=systemd-modules-load.service
Before=swap.target shutdown.target
Conflicts=shutdown.target

[Service]
Type=oneshot
ExecStart=$SCRIPT_PATH
RemainAfterExit=yes
ExecStop=/usr/sbin/swapoff /dev/zram0

[Install]
WantedBy=swap.target multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable zram-swap.service >/dev/null 2>&1
}

RemoveZramAutostart() {
    local SCRIPT_PATH="/usr/local/bin/zram-autostart.sh"
    local SERVICE_PATH="/etc/systemd/system/zram-swap.service"
    
    if [ -f "$SERVICE_PATH" ]; then
        systemctl disable zram-swap.service >/dev/null 2>&1
        systemctl stop zram-swap.service >/dev/null 2>&1
        rm -f "$SERVICE_PATH"
        rm -f "$SCRIPT_PATH"
        systemctl daemon-reload
    fi
}

CheckAutostartEnabled() {
    if [ -f /etc/systemd/system/zram-swap.service ]; then
        if systemctl is-enabled zram-swap.service >/dev/null 2>&1; then
            return 0
        fi
    fi
    return 1
}

EnableZram() {
    local SIZE_MB=$1
    local ALGO=$2
    local SAVE_CONFIG=${3:-true}
    
    DisableZram
    sleep 0.5
    
    modprobe zram num_devices=1 2>/dev/null
    sleep 0.5
    
    if [ ! -b /dev/zram0 ]; then
        dialog --backtitle "$BACKTITLE" \
               --title "ERROR" \
               --msgbox "Cannot create /dev/zram0\n\nZRam module may not be available\nin your kernel." 8 45 > "$CURR_TTY"
        return 1
    fi
    
    if [ -f /sys/block/zram0/comp_algorithm ]; then
        if grep -q "$ALGO" /sys/block/zram0/comp_algorithm; then
            echo "$ALGO" > /sys/block/zram0/comp_algorithm 2>/dev/null
        else
            dialog --backtitle "$BACKTITLE" \
                   --title "Warning" \
                   --msgbox "Algorithm '$ALGO' not supported!\n\nUsing default algorithm..." 7 45 > "$CURR_TTY"
        fi
    fi
    
    local SIZE_BYTES=$((SIZE_MB * 1024 * 1024))
    echo "$SIZE_BYTES" > /sys/block/zram0/disksize
    
    mkswap /dev/zram0 >/dev/null 2>&1
    swapon -p 5 /dev/zram0
    
    if [ $? -eq 0 ]; then
        local ACTUAL_ALGO=$(cat /sys/block/zram0/comp_algorithm 2>/dev/null | grep -oP '\[\K[^\]]+')
        [ -z "$ACTUAL_ALGO" ] && ACTUAL_ALGO="$ALGO"
        
        if [ "$SAVE_CONFIG" = true ]; then
            SaveZramConfig "$SIZE_MB" "$ACTUAL_ALGO"
            SetupZramAutostart
        fi
        
        dialog --backtitle "$BACKTITLE" \
               --title "✓ Success" \
               --msgbox "ZRam successfully enabled!\n\n  • Size      : ${SIZE_MB} MB\n  • Algorithm : ${ACTUAL_ALGO}\n  • Priority  : 5 (High)\n  • Autostart : Enabled\n\nZRam is now active and will start\nautomatically on every boot." 15 45 > "$CURR_TTY"
        return 0
    else
        dialog --backtitle "$BACKTITLE" \
               --title "ERROR" \
               --msgbox "Failed to enable ZRam!\n\nPlease check system logs." 7 45 > "$CURR_TTY"
        return 1
    fi
}

SelectZramSize() {
    local SYSTEM_RAM=$1
    local DEFAULT_SIZE=$2
    
    local CHOICES=()
    
    CHOICES+=("${DEFAULT_SIZE}" "★ ${DEFAULT_SIZE} MB │ Recommended")
    
    if [ 256 -le $SYSTEM_RAM ] && [ 256 -ne $DEFAULT_SIZE ]; then
        CHOICES+=("256" "  256 MB │ Minimum")
    fi
    
    if [ 384 -le $SYSTEM_RAM ] && [ 384 -ne $DEFAULT_SIZE ]; then
        CHOICES+=("384" "  384 MB │ Light")
    fi
    
    if [ 512 -le $SYSTEM_RAM ] && [ 512 -ne $DEFAULT_SIZE ]; then
        CHOICES+=("512" "  512 MB │ Balanced")
    fi
    
    if [ 768 -le $SYSTEM_RAM ] && [ 768 -ne $DEFAULT_SIZE ]; then
        CHOICES+=("768" "  768 MB │ Enhanced")
    fi
    
    if [ 1024 -le $SYSTEM_RAM ] && [ 1024 -ne $DEFAULT_SIZE ]; then
        CHOICES+=("1024" " 1024 MB │ High (1GB)")
    fi
    
    if [ 1536 -le $SYSTEM_RAM ] && [ 1536 -ne $DEFAULT_SIZE ]; then
        CHOICES+=("1536" " 1536 MB │ Very High (1.5GB)")
    fi
    
    if [ 2048 -le $SYSTEM_RAM ] && [ 2048 -ne $DEFAULT_SIZE ]; then
        CHOICES+=("2048" " 2048 MB │ Maximum (2GB)")
    fi
    
    local OPTION_COUNT=$((${#CHOICES[@]} / 2))
    local MENU_HEIGHT=$((OPTION_COUNT + 7))
    
    local SELECTION
    SELECTION=$(dialog --backtitle "$BACKTITLE" \
                       --title "[ ZRAM SIZE ]" \
                       --default-item "$DEFAULT_SIZE" \
                       --menu "RAM: ${SYSTEM_RAM}MB │ Recommended: ${DEFAULT_SIZE}MB" \
                       $MENU_HEIGHT 50 $OPTION_COUNT \
                       "${CHOICES[@]}" \
                       2>&1 > "$CURR_TTY")
    
    echo "$SELECTION"
}

SelectAlgorithm() {
    local DEFAULT_ALGO=$1
    local ALGOS=$(GetAvailableAlgorithms)
    
    local CHOICES=()
    local ALGO_COUNT=0
    
    while IFS= read -r algo; do
        ((ALGO_COUNT++))
        if [ "$algo" == "$DEFAULT_ALGO" ]; then
            case "$algo" in
                lz4)
                    CHOICES+=("$algo" "★ lz4     │ Ultra-fast")
                    ;;
                lzo)
                    CHOICES+=("$algo" "★ lzo     │ Fast & balanced")
                    ;;
                lzo-rle)
                    CHOICES+=("$algo" "★ lzo-rle │ Sparse data")
                    ;;
                zstd)
                    CHOICES+=("$algo" "★ zstd    │ High compression")
                    ;;
                deflate)
                    CHOICES+=("$algo" "★ deflate │ Max compression")
                    ;;
                842)
                    CHOICES+=("$algo" "★ 842     │ HW accelerated")
                    ;;
                *)
                    CHOICES+=("$algo" "★ $algo   │ Fastest")
                    ;;
            esac
        else
            case "$algo" in
                lz4)
                    CHOICES+=("$algo" "  lz4     │ Ultra-fast")
                    ;;
                lzo)
                    CHOICES+=("$algo" "  lzo     │ Fast & balanced")
                    ;;
                lzo-rle)
                    CHOICES+=("$algo" "  lzo-rle │ Sparse data")
                    ;;
                zstd)
                    CHOICES+=("$algo" "  zstd    │ High compression")
                    ;;
                deflate)
                    CHOICES+=("$algo" "  deflate │ Max compression")
                    ;;
                842)
                    CHOICES+=("$algo" "  842     │ HW accelerated")
                    ;;
                *)
                    CHOICES+=("$algo" "  $algo   │ Available")
                    ;;
            esac
        fi
    done <<< "$ALGOS"
    
    local MENU_HEIGHT=$((ALGO_COUNT + 7))
    
    local SELECTION
    SELECTION=$(dialog --backtitle "$BACKTITLE" \
                       --title "[ ALGORITHM ]" \
                       --default-item "$DEFAULT_ALGO" \
                       --menu "Fastest: ${DEFAULT_ALGO} │ ★ = Recommended" \
                       $MENU_HEIGHT 50 $ALGO_COUNT \
                       "${CHOICES[@]}" \
                       2>&1 > "$CURR_TTY")
    
    echo "$SELECTION"
}

ShowZramInfo() {
    local SYSTEM_RAM=$(GetSystemRAM)
    local STATUS_INFO=$(CheckZramStatus)
    
    IFS='|' read -r STATUS SIZE ALGO USED <<< "$STATUS_INFO"
    
    local STATUS_TEXT
    if [ "$STATUS" == "ACTIVE" ]; then
        local COMPRESSION_RATIO="N/A"
        
        if [ -f /sys/block/zram0/mm_stat ]; then
            local ORIG_SIZE=$(awk '{print $1}' /sys/block/zram0/mm_stat 2>/dev/null)
            local COMP_SIZE=$(awk '{print $2}' /sys/block/zram0/mm_stat 2>/dev/null)
            
            if [ "$COMP_SIZE" -gt 0 ] 2>/dev/null; then
                COMPRESSION_RATIO=$(awk "BEGIN {printf \"%.1f:1\", $ORIG_SIZE/$COMP_SIZE}")
            fi
        fi
        
        local PERCENT_RAM=$((SIZE * 100 / SYSTEM_RAM))
        
        local AUTOSTART_STATUS="○"
        if CheckAutostartEnabled; then
            AUTOSTART_STATUS="●"
        fi
        
        STATUS_TEXT="╔═══════════ ZRAM ACTIVE ═══════════╗
║ Status      : ● ACTIVE
║ Size        : ${SIZE} MB
║ Algorithm   : ${ALGO}
║ Used        : ${USED} MB
║ Compression : ${COMPRESSION_RATIO}
║ Priority    : 5 (High)
║ Autostart   : ${AUTOSTART_STATUS}
╠═══════════ SYSTEM INFO ═══════════╣
║ Total RAM   : ${SYSTEM_RAM} MB
║ ZRam Usage  : ${PERCENT_RAM}% of RAM
╠════════════════════════════════════╣
║ ZRam is compressing memory and
║ improving system performance.
║ Will auto-start on reboot.
╚════════════════════════════════════╝"
    else
        local OPTIMAL_SIZE=$(GetOptimalZramSize "$SYSTEM_RAM")
        local FASTEST_ALGO=$(GetFastestAlgorithm)
        
        local AUTOSTART_STATUS="Not configured"
        if CheckAutostartEnabled; then
            AUTOSTART_STATUS="Pending activation"
        fi
        
        STATUS_TEXT="╔═══════════ ZRAM INACTIVE ═════════╗
║ Status      : ○ INACTIVE
║ Autostart   : ${AUTOSTART_STATUS}
╠═══════════ SYSTEM INFO ═══════════╣
║ Total RAM   : ${SYSTEM_RAM} MB
╠════════ RECOMMENDED ══════════════╣
║ Size        : ${OPTIMAL_SIZE} MB (50% RAM)
║ Algorithm   : ${FASTEST_ALGO}
╠════════════════════════════════════╣
║ ZRam is not active.
║ Use 'Enable' to activate.
╚════════════════════════════════════╝"
    fi
    
    dialog --backtitle "$BACKTITLE" \
           --title "[ INFO ]" \
           --msgbox "$STATUS_TEXT" 20 45 > "$CURR_TTY"
}

MainMenu() {
    local SYSTEM_RAM=$(GetSystemRAM)
    local OPTIMAL_SIZE=$(GetOptimalZramSize "$SYSTEM_RAM")
    local FASTEST_ALGO=$(GetFastestAlgorithm)
    
    while true; do
        local STATUS_INFO=$(CheckZramStatus)
        IFS='|' read -r STATUS SIZE ALGO USED <<< "$STATUS_INFO"
        
        local STATUS_DISPLAY
        local STATUS_ICON
        if [ "$STATUS" == "ACTIVE" ]; then
            STATUS_DISPLAY="${SIZE}MB ${ALGO}"
            STATUS_ICON="●"
        else
            STATUS_DISPLAY="Inactive"
            STATUS_ICON="○"
        fi
        
        local CHOICE
        CHOICE=$(dialog --backtitle "$BACKTITLE" \
                       --title "[ MAIN MENU ]" \
                       --ok-label "Select" \
                       --cancel-label "Exit" \
                       --menu "RAM: ${SYSTEM_RAM}MB │ ZRam: ${STATUS_ICON} ${STATUS_DISPLAY}" \
                       15 55 5 \
                       1 "► Info & Statistics" \
                       2 "► Enable (Quick)" \
                       3 "► Enable (Custom)" \
                       4 "► Disable ZRam" \
                       5 "► Exit" \
                       2>&1 > "$CURR_TTY")
        
        local RET=$?
        
        if [ $RET -ne 0 ]; then
            ExitMenu
        fi
        
        case $CHOICE in
            1)
                ShowZramInfo
                ;;
            2)
                if [ "$STATUS" == "ACTIVE" ]; then
                    dialog --backtitle "$BACKTITLE" \
                           --title "[ ACTIVE ]" \
                           --msgbox "ZRam is running!\n\nCurrent: ${SIZE}MB, ${ALGO}, ${USED}MB used\n\nDisable first to reconfigure." 9 50 > "$CURR_TTY"
                else
                    dialog --backtitle "$BACKTITLE" \
                           --title "[ QUICK SETUP ]" \
                           --yesno "Enable with optimal settings?\n\nSize: ${OPTIMAL_SIZE}MB │ Algo: ${FASTEST_ALGO}\nPriority: 5 │ Autostart: Yes\n\nAuto-detected for best performance.\n\nContinue?" 11 50 > "$CURR_TTY"
                    
                    if [ $? -eq 0 ]; then
                        EnableZram "$OPTIMAL_SIZE" "$FASTEST_ALGO"
                    fi
                fi
                ;;
            3)
                if [ "$STATUS" == "ACTIVE" ]; then
                    dialog --backtitle "$BACKTITLE" \
                           --title "[ ACTIVE ]" \
                           --msgbox "ZRam is running!\n\nCurrent: ${SIZE}MB, ${ALGO}\n\nDisable first to reconfigure." 8 50 > "$CURR_TTY"
                else
                    local SELECTED_SIZE=$(SelectZramSize "$SYSTEM_RAM" "$OPTIMAL_SIZE")
                    if [ -n "$SELECTED_SIZE" ]; then
                        local SELECTED_ALGO=$(SelectAlgorithm "$FASTEST_ALGO")
                        if [ -n "$SELECTED_ALGO" ]; then
                            EnableZram "$SELECTED_SIZE" "$SELECTED_ALGO"
                        fi
                    fi
                fi
                ;;
            4)
                if [ "$STATUS" == "INACTIVE" ]; then
                    dialog --backtitle "$BACKTITLE" \
                           --title "[ INACTIVE ]" \
                           --msgbox "ZRam is not active.\n\nUse 'Enable' to activate." 7 45 > "$CURR_TTY"
                else
                    dialog --backtitle "$BACKTITLE" \
                           --title "[ CONFIRM ]" \
                           --yesno "Disable ZRam?\n\nCurrent: ${SIZE}MB, ${ALGO}, ${USED}MB used\n\nThis will:\n• Free ${SIZE}MB compressed space\n• Remove autostart\n• Require manual re-enable\n\nProceed?" 13 50 > "$CURR_TTY"
                    
                    if [ $? -eq 0 ]; then
                        DisableZram
                        dialog --backtitle "$BACKTITLE" \
                               --title "[ DISABLED ]" \
                               --msgbox "ZRam disabled successfully.\n\nAutostart removed.\nWill not start on next boot." 8 45 > "$CURR_TTY"
                    fi
                fi
                ;;
            5)
                ExitMenu
                ;;
        esac
    done
}

AutoLoadZram() {
    local CONFIG=$(LoadZramConfig)
    if [ $? -eq 0 ]; then
        IFS='|' read -r SIZE ALGO <<< "$CONFIG"
        if [ -n "$SIZE" ] && [ -n "$ALGO" ]; then
            modprobe zram num_devices=1 2>/dev/null
            sleep 0.5
            
            if [ -b /dev/zram0 ]; then
                if [ -f /sys/block/zram0/comp_algorithm ]; then
                    if grep -q "$ALGO" /sys/block/zram0/comp_algorithm; then
                        echo "$ALGO" > /sys/block/zram0/comp_algorithm 2>/dev/null
                    fi
                fi
                
                local SIZE_BYTES=$((SIZE * 1024 * 1024))
                echo "$SIZE_BYTES" > /sys/block/zram0/disksize
                mkswap /dev/zram0 >/dev/null 2>&1
                swapon -p 5 /dev/zram0 2>/dev/null
            fi
        fi
    fi
}



sudo chmod 666 "$CURR_TTY"
sudo chmod 666 /dev/uinput
printf "\e[?25l" > "$CURR_TTY"
clear > "$CURR_TTY"
dialog --clear
trap ExitMenu EXIT

export SDL_GAMECONTROLLERCONFIG_FILE="/opt/inttools/gamecontrollerdb.txt"
pgrep -f gptokeyb | sudo xargs kill -9 2>/dev/null
/opt/inttools/gptokeyb -1 "ZRam_Manager.sh" -c "/opt/inttools/keys.gptk" > /dev/null 2>&1 &

STATUS_INFO=$(CheckZramStatus)
IFS='|' read -r STATUS SIZE ALGO USED <<< "$STATUS_INFO"

if [ "$STATUS" == "INACTIVE" ]; then
    CONFIG=$(LoadZramConfig)
    if [ $? -eq 0 ]; then
        AutoLoadZram
    fi
fi

MainMenu

